### ISSUE TITLE
use ::

### ISSUE THREAD

**Issue by jacobbien** [sangwon-hyun/flowmix#1]
I get errors such as `could not find function "mclapply"` when I run the `covarem_once` function from `flowcy`.  When I first run `library(parallel)` this error goes away.  I believe this means you are using `mclapply` in the package rather than `parallel::mclapply`.  Beyond making this change, all functions from other packages should be handled similarly.  Refer to [this section of Hadley Wickham's R Packages book](http://r-pkgs.had.co.nz/namespace.html#imports) for how to handle functions that are from other R packages.

**Comment by sangwon-hyun** [comment]
Thanks for the reminder about this! I'll work on this soon.
