### ISSUE TITLE
Failed example for high-dimensional example with cv_flowmix

### ISSUE THREAD

**Issue by simengshao** [sangwon-hyun/flowmix#6]
I created an example where cv_flowmix runs into problems:
https://www.dropbox.com/s/wr1zslc775rz6i5/cv_flowmix_example.R?dl=0

**Comment by sangwon-hyun** [comment]
I checked that this code now works if you use `cv.gridsize=2`. Could you check if it works on your computer now (and append your error message if it still doesn't)? 

I'm curious if there is an error for specific values of lambda. The simpler thing to check is something like this:

```
res = flowmix(ylist,
              countslist = NULL,
              X = X,
              maxdev = 1E10,
              numclust = 2,
              prob_lambda = 0.001,
              mean_lambda = 0.001,
              nrep = 1)
```

**Comment by simengshao** [comment]
I tried the following:
```
cv_gridsize = 2
prob_lambdas =  logspace(min = 0.001, max = maxres$alpha, length = cv_gridsize)
mean_lambdas = logspace(min = 0.001, max = maxres$beta, length = cv_gridsize)

# Parallel jobs are halted when cross-validation
cvres = cv.flowmix(ylist = ylist,
                   countslist = NULL,
                   X = X,
                   maxdev = 1E10,
                   numclust = 2,
                   prob_lambdas = prob_lambdas,
                   mean_lambdas = mean_lambdas,
                   nrep = 5,
                   nfold = 5,
                   destin = destin,
                   mc.cores = 8,
                   blocksize = 5,
                   save_meta = TRUE)
```
It still reports problem on my end:

> In parallel::mclapply(1:nrow(iimat), function(ii) { :
  scheduled cores 1, 2, 3, 4, 5, 6, 7, 8 did not deliver results, all values of the jobs will be affected



But `flowmix` works for all lambda values.

> I'm curious if there is an error for specific values of lambda. 

`cv_gridsize = 2` means it is only taking the smallest and largest value. It would be interesting if the extreme lambdas work but values in the middle would not work...

**Comment by sangwon-hyun** [comment]
Great, we're getting closer to identifying the problem! 

Can you 
(1) update your package installation to the latest one, and 
(2) add a set.seed(585823) directly before the `cv.flowmix()` call, and  
(2) try running it with `mc.cores=1`? 

And if it still fails, you should be able to show me the error message and the iteration number where it failed!

**Comment by sangwon-hyun** [comment]
@simengshao Did this work?

**Comment by simengshao** [comment]
Hi sorry for the late reply. With mc.cores = 1 it works, but still does not work when mc.cores is set to any integers >1 on my mac OS device. Thanks anyway!
